namespace CatchUpPlatform.API.News.Interfaces.REST.Resources;


/// <summary>
/// Resource for creating a favorite source
/// </summary>
/// <param name="NewsApiKey"> The news api key generated by the news provider </param>
/// <param name="SourceId"> The news provider source id</param>
public record CreateFavoriteSourceResource(string NewsApiKey, string SourceId);